### PR TITLE
[Azure] Apply new SDK and fix of getting image list

### PR DESCRIPTION
**Pull request by ish-hcc**
### Apply new SDK
- Get rid of deprecated SDK and apply new armXXXXX SDK.
- Tested for all handlers with CLI and AdminWeb.
- k8s upgrade is also working.
- We can now use more functions in SDK.
- Need to change some directly called APIs to SDK's functions when needed.

### Fix of getting image list
- Only get latest version for same types of images.
- Previous PR (getting all of version, deprecated SDK): 55693 images, 71 minutes
- Current PR (getting latest version, new SDK): 19381 images, 50 minutes (about -20 minutes)

### CODE REVIEW

**Comment by powerkimhub** [comment]
@sykim-etri 

<br>

- K8S 관련 참고해주시기 바랍니다. 
- Test 진행된 사항이므로 Image 관련된 부분 검토 후에 Merge 예정입니다.
- @sykim-etri  Azure:K8S 관련 기능 점검은 Merge 후에 하시는 것이 좋을 듯합니다.

<br>

> ## Azure
> ### Apply new SDK
> * Get rid of deprecated SDK and apply new armXXXXX SDK.
> * Tested for all handlers with CLI and AdminWeb.
> * k8s upgrade is also working.
> * We can now use more functions in SDK.
> * Need to change some directly called APIs to SDK's functions when needed.

**Comment by powerkimhub** [comment]
@ish-hcc 

<br>

- 다음 링크에 PR 적용 현황 업데이트 부탁드립니다. 
  - https://github.com/cloud-barista/cb-spider/wiki/What-is-the-CSP-SDK-API-Version-of-drivers

**Comment by ish-hcc** [comment]
@powerkimhub 업데이트 했습니다. 감사합니다.

**Comment by powerkimhub** [comment]
> @powerkimhub 업데이트 했습니다. 감사합니다.

- @ish-hcc 캄사합니다.

**Comment by ish-hcc** [comment]
Last test result: 19450 images / 1857 seconds

**Review by powerkimhub — APPROVED** [review]

**Pull request merged**
